In [1]:
import tensorflow as tf
import numpy as np
from datetime import datetime

2022-11-21 08:48:01.958637: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:
2022-11-21 08:48:01.958696: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:
2022-11-21 08:48:01.958701: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


In [2]:
tf.compat.v1.disable_eager_execution()

In [3]:
# create two constants: a and b
a = tf.constant(4)
b = tf.constant(3)

# perform a computation
c = a + b
print(c) # print the shape of c

print(c) # print the actual result

Tensor("add:0", shape=(), dtype=int32)
Tensor("add:0", shape=(), dtype=int32)


In [4]:
# reset the graph
tf.compat.v1.reset_default_graph()

In [5]:
a = tf.compat.v1.constant(1)
print(a.shape)

()


In [6]:
a = tf.compat.v1.constant([1,2,3,4,5])
first_three_elem = a[3:]
fourth_elem = a[3]

print(first_three_elem)

Tensor("strided_slice:0", shape=(2,), dtype=int32)


In [7]:
print(fourth_elem)

Tensor("strided_slice_1:0", shape=(), dtype=int32)


In [8]:
a = tf.compat.v1.constant([1.0, 1.1, 2.1, 3.1], dtype = tf.float32, name='a_const')
print(a)

Tensor("a_const:0", shape=(4,), dtype=float32)


In [9]:
a = tf.compat.v1.placeholder(shape=(1,3), dtype=tf.float32)
b = tf.constant([[10,10,10]], dtype=tf.float32)

c = a + b

sess = tf.compat.v1.Session()
#feed_dict={a:[[0.1, 0.2, 0.3,0.4]]}
#print(feed_dict)
#resss = sess.run(feed_dict)
res = sess.run(c, feed_dict={a:[[0.1, 0.2, 0.3]]})
print(res)

[[10.1 10.2 10.3]]


2022-11-21 08:48:02.609953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-11-21 08:48:02.668633: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-21 08:48:02.668977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:0b:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.815GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 312.97GiB/s
2022-11-21 08:48:02.669065: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:
2022-11-21 08:48:02.680061: I tensorflow/stream_executor/platform/default/dso_

In [10]:
tf.compat.v1.reset_default_graph()

In [11]:
a = tf.compat.v1.placeholder(shape=(None,3), dtype = tf.float32)
b = tf.compat.v1.placeholder(shape=(None,3), dtype = tf.float32)

c = a+b

sess = tf.compat.v1.Session()

res = sess.run(c, feed_dict = {a:[[0.1, 0.2, 0.3]], b:[[10 ,20, 30]]})

print(res)

[[10.1 20.2 30.3]]


2022-11-21 08:48:02.861248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-21 08:48:02.861285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      


In [12]:
v_a = np.array(([1,2,3],[4,5,6]))
v_b = np.array(([6,5,4],[3,2,1]))

res = sess.run(c, feed_dict={a:v_a, b:v_b})
print(res)

[[7. 7. 7.]
 [7. 7. 7.]]


In [13]:
tf.compat.v1.reset_default_graph()

In [14]:
tf.compat.v1.reset_default_graph()

var = tf.compat.v1.get_variable("first_variable", shape=[1,3], dtype=tf.float32, initializer=tf.compat.v1.glorot_uniform_initializer)

init_val = np.array([4,5])
var2 = tf.compat.v1.get_variable("second_variable", shape=[1,2], dtype=tf.int32, initializer=tf.compat.v1.constant_initializer(init_val))

sess = tf.compat.v1.Session()
sess.run(tf.compat.v1.global_variables_initializer())

print(sess.run(var))
print(sess.run(var2))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[[ 0.6492783   0.23748434 -0.65963066]]
[[4 5]]


2022-11-21 08:48:02.893700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-21 08:48:02.893727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      


In [15]:
var2 = tf.compat.v1.get_variable("variable", shape=[1,2], trainable=False, dtype=tf.int32)

In [16]:
print(tf.compat.v1.global_variables())

[<tf.Variable 'first_variable:0' shape=(1, 3) dtype=float32>, <tf.Variable 'second_variable:0' shape=(1, 2) dtype=int32>, <tf.Variable 'variable:0' shape=(1, 2) dtype=int32>]


In [17]:
# reset_graph 
# get_varialbe에서 Session을 하려면 initializer을 해줘야함

tf.compat.v1.reset_default_graph()

const1 = tf.compat.v1.constant(3.0, name='constant1')

var = tf.compat.v1.get_variable("variable1", shape=[1,2], dtype=tf.float32)
var2 = tf.compat.v1.get_variable("variable2", shape=[1,2], trainable=False, dtype=tf.float32)

op1 = const1 * var
op2 = op1 + var2
op3 = tf.compat.v1.reduce_mean(op2)

sess = tf.compat.v1.Session()
sess.run(tf.compat.v1.global_variables_initializer())
sess.run(op3)

2022-11-21 08:48:02.942312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-21 08:48:02.942344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      


-0.7455147

In [18]:
tf.compat.v1.reset_default_graph()

np.random.seed(10)
tf.compat.v1.compat.v1.set_random_seed(10)

W, b = 0.5, 1.4
# create a dataset of 100 examples
X = np.linspace(0,100, num=100)
# add random noise to the y labels
y = np.random.normal(loc=W * X + b, scale=2.0, size=len(X))

# create the placeholders
x_ph = tf.compat.v1.placeholder(shape=[None,], dtype=tf.float32)
y_ph = tf.compat.v1.placeholder(shape=[None,], dtype=tf.float32)

# create the variables.
v_weight = tf.compat.v1.get_variable("weight", shape=[1], dtype=tf.float32)
v_bias = tf.compat.v1.get_variable("bias", shape=[1], dtype=tf.float32)

# linear computation
out = v_weight * x_ph + v_bias

# compute the Mean Squared Error
loss = tf.compat.v1.reduce_mean((out - y_ph)**2)

# optimizer
opt = tf.compat.v1.train.AdamOptimizer(0.4).minimize(loss)


tf.compat.v1.summary.scalar('MSEloss', loss)
tf.compat.v1.summary.histogram('model_weight', v_weight)
tf.compat.v1.summary.histogram('model_bias', v_bias)
all_summary = tf.compat.v1.summary.merge_all()

now = datetime.now()
clock_time = "{}_{}.{}.{}".format(now.day, now.hour, now.minute, now.second)
file_writer = tf.compat.v1.summary.FileWriter('log_dir/'+clock_time, tf.compat.v1.get_default_graph())


# create the session
session = tf.compat.v1.Session()
session.run(tf.compat.v1.global_variables_initializer())

# loop to train the parameters
for ep in range(210):
    # run the optimizer and get the loss
    train_loss, _, train_summary = session.run([loss, opt, all_summary], feed_dict={x_ph:X, y_ph:y})
    file_writer.add_summary(train_summary, ep)
 
    # print epoch number and loss
    if ep % 40 == 0:
        print('Epoch: %3d, MSE: %.4f, W: %.3f, b: %.3f' % (ep, train_loss, session.run(v_weight), session.run(v_bias)))
        
print('Final weight: %.3f, bias: %.3f' % (session.run(v_weight), session.run(v_bias)))
file_writer.close()

Epoch:   0, MSE: 4572.0996, W: 1.295, b: -0.797


2022-11-21 08:48:03.008703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-21 08:48:03.008727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      


Epoch:  40, MSE: 5.8447, W: 0.497, b: -1.052
Epoch:  80, MSE: 4.8327, W: 0.533, b: -0.243
Epoch: 120, MSE: 4.2012, W: 0.515, b: 0.458
Epoch: 160, MSE: 3.8903, W: 0.507, b: 1.004
Epoch: 200, MSE: 3.7699, W: 0.502, b: 1.372
Final weight: 0.501, bias: 1.433
